name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/ecoflow_exporter
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}

      - name: Log in to registry
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}"

      # - name: Delete package after PR merge
      #   if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
      #   uses: smartsquaregmbh/delete-old-packages@v0.6.0
      #   with:
      #     type: container
      #     user: ${{ github.repository_owner }}
      #     keep: 0
      #     names: |
      #       ecoflow_exporter
      #     version-pattern: "^pr\\-${{github.event.pull_request.number}}$"
